// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
// Lovable Cloud typically exposes the anon key as VITE_SUPABASE_ANON_KEY.
// Keep backward-compatibility with older projects that used VITE_SUPABASE_PUBLISHABLE_KEY.
const SUPABASE_ANON_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) as
  | string
  | undefined;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  // Fail fast with a useful message instead of the opaque "supabaseUrl is required".
  throw new Error(
    'Backend configuration missing: please enable/configure Lovable Cloud so VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are available.'
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
